### ISSUE TITLE
Request for comment: Revidert månedskalender

### ISSUE THREAD

**Issue by mortnod** [petterhol/pdog.no#267]
Takk for [tankevekkende artikkel om datering](https://pdog.no/ukekalender/). Det er urovekkende hvor lenge det er siden forrige gang det nåværende kalendersystemet ble patchet, så det var på høy tid med en oppdatering.

Jeg synes den foreslåtte løsningen tar tak i mye av det som er uergonomisk med dagens system. Samtidig er det aspekter ved dagens løsning jeg liker og som jeg hadde foretrukket om ble ivaretatt. Jeg ønsker derfor å oppsummere det jeg liker/ikke liker ved ukeskalenderen, for deretter å foreslå et alternativ.

# Fordeler med ukekalender

### Fjerner irregulariteten av lengden til måneder
En måned kan bestå av 28, 30, eller 31 dager. Dette er utrolig lite tilfredsstillende. Hvis noen hadde spurt meg hvor mange dager det er i juli hadde jeg ikke klart å svare på stående fot. Ukeskalender fikser dette problemet, og det er helt nydelig 💅

### Tett knytning mellom dato og ukedag
Med ukeskalender unngår man forskyvningen av merkedager. Dermed vil 17. mai, nyttårsaften og bursdager ligge på samme ukedag hvert år.

# Ulemper med ukekalender

### Måned er en nyttig tidsenhet
Timer, dager, uker, måneder, kvartaler og år. Alle er ord vi bruker for å kommunisere en mengde tid i forskjellig granularitet.

Å fjerne konseptet måned innebærer å gå rett fra uke til kvartal, et svært stor sprang i granularitet. Jeg synes dette er et stort tap for enkel og presis kommunikasjon. 

### Lite rom for særpreg mellom uker
Endringen i klima fra måned til måned er merkbar. Samme kan ikke sies om uke til uke. Dermed vil det også bli vanskeligere å skape klare, distinkte skillelinjer.

En vanlig strategi for å gjøre noe mer "huskbart" er å navngi det. Men siden det er så mange uker, og det er så lite som skiller dem, vil det bli en utfordrende oppgave.

### Store tall er mindre håndgripelige enn små tall
Menneskehjernen sliter med å håndtere store tall. Forskning har f.eks. vist at alt større enn 5 er for stort til at vi gjenkjenner det intuitivt. Allerede da må vi hoppe over på nye strategier for å beholde kontrollen.

Jeg vil argumentere for at 52/53 er for stort til at menneskehjernen klarer å holde tunga rett i munn. Det langt fra opplagt for meg hva slags assosiasjoner jeg skal ha til uke 37, for eksempel.

# Foreslått løsning: Revidert månedskalender

Målet med forslaget er å beholde fordelene ved konseptet måned, men samtidig løse de største problemene dagens månedskonsept innebærer, nemlig irregulariteten og forskyvningen.

### Hvordan fungerer det?

1. Alle måneder er nøyaktig 4 uker lange, altså 28 dager.
2. Vi innfører én ekstra måned ved navn «Dogus». Også den måneden er 28 dager lang.
3. Den observante leser vil se at `28 * 13 = 364 dager`. Da gjenstår det én dag. Den gjenværende dagen kalles for «Pausen».
	* I skuddår bli Pausen forlenget med en ekstra dag
	* Pausen vil bli et naturlig tilskudd til dagens nyttårsfeiring.

### Notasjon
Det er ønskelig å legge seg så tett på ISO 8601 som mulig. Derfor foreslås følgende:

**27. februar 2023** → 2023-02-27
**5. dogus 2023** → 2023-13-05
**Pausen** → 2023-00-01
**Ekstrapausen** → 2023-00-02

### Fordeler
* Beholder konseptet måned, da det har vist seg å være nyttig for effektiv kommunikasjon
* Fjerner irregulariteten og forskyvningen dagens måneder skaper

### Ulemper
* Konseptet kvartal svekkes siden 13 ikke er delbart på 4
* Kombinasjonen av måneder og Pausen er ikke like «clean» som å kun forholde seg til uker.

Beste hilsen,
M-emu

**Comment by petterhol** [comment]
@Stigjb

**Comment by Stigjb** [comment]
Vi må gjøre noe med tekstrepresentasjonen. Det foreslåtte `2023-02-27` ser ut som en ordinær Å-M-D-dato, så de nye Morten-månedene må ha en markør som viser at de skal tolkes annerledes. Hva med en skråstrek? Dermed er `2023-02-27`, som i dag, utvetydig den 27. februar etter gjengs forståelse, mens `2023-/02-27`, `2023-/13-05` og `2023-/00-01` er utvetydige datoer i Mortens system.

**Comment by petterhol** [comment]
Hei @mortnod 

Tusen takk for at du engasjerer deg.

Jeg har funnet ut at du har [plagiert en idé av Dave Gorman](https://www.youtube.com/watch?v=rTJ5g4S_U5E). Siden plagiat er i vinden for tiden, har jeg ikke noe annen mulighet enn å avvise forslaget ditt.

Dog.
